trigger:
  branches:
    include:
      - master
  tags:
    include: ['*']

pr:
  branches:
    include: ['*']

variables:
  RUST_BACKTRACE: '1'
  RUSTFLAGS: '-C debug-assertions'

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      all:
        CI_JOB: test
        CI_JOB_ARGS: .
  steps:
    - template: '.ci/test.yml'
